//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XboxWCFService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UTBodyDataEntities : DbContext
    {
        public UTBodyDataEntities()
            : base("name=UTBodyDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BodyData> BodyDatas { get; set; }
    
        public virtual int uspInsertBodyData(string joints, string jointPoints, Nullable<System.DateTime> timestamp)
        {
            var jointsParameter = joints != null ?
                new ObjectParameter("Joints", joints) :
                new ObjectParameter("Joints", typeof(string));
    
            var jointPointsParameter = jointPoints != null ?
                new ObjectParameter("JointPoints", jointPoints) :
                new ObjectParameter("JointPoints", typeof(string));
    
            var timestampParameter = timestamp.HasValue ?
                new ObjectParameter("timestamp", timestamp) :
                new ObjectParameter("timestamp", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspInsertBodyData", jointsParameter, jointPointsParameter, timestampParameter);
        }
    }
}
