//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XboxWCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class BodyData
    {
        public int UserID { get; set; }
        public string Joints { get; set; }
        public string JointPoints { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string UserName { get; set; }
        public string SessionName { get; set; }
    }
}
